### PR TITLE
Backticks can be nested; remove from BUGS

### PR DESCRIPTION
**Pull request by Krush206**

### CODE REVIEW

**Comment by Krush206** [comment]
This nesting style can lead to confusion, since it must be doubled (as in Bourne Shells). It'd be nice to have a `$()` wrapper for it.

**Comment by Krush206** [comment]
Apparently, this nesting style is very different. I can't seem to find a way to nest three or more commands, but this works: echo "\`echo "\\\`"pwd"\\\`"\`"

Either there's no way to do so or I'm failing to understand.

**Comment by Krush206** [comment]
``echo "`{echo,"'`pwd`'"}`"``
This works too, but still no luck for multiple nesting.

**Comment by Krush206** [comment]
``echo "`echo "\"'`echo "\`"pwd"\`"`'\""`"``
For three nests, this works. This is very complicated.

I'm still investigating further.

**Comment by Krush206** [comment]
``echo "`echo "\"'`echo "\"'\''`echo "\`"pwd"\`"`'\''\""`'\""`"``
Finally made four nests. This nesting style is ridiculous, but does work.

**Comment by Krush206** [comment]
https://bwass.org/bucket/IMG_20221127_093248.jpg
``echo "`echo "\"'`echo "\"'\''`echo "\"'\'\\\'\''`echo "\"'\'\\\'\\\\\\\'\\\'\''`echo "\`"pwd"\`"`'\'\\\'\\\\\\\'\\\'\''\""`'\'\\\'\''\""`'\''\""`'\""`"``

**Comment by Krush206** [comment]
``echo "`echo "\"\`"echo "\"\\\"\\\`\""echo "\"\\\"\\\\\\\"\\\\\\\`\\\"\""echo "\"\\\"\\\\\\\"\\\\\\\\\\\\\\\"\\\\\\\\\\\\\\\`\\\\\\\"\\\"\""echo "\"\\\"\\\\\\\"\\\\\\\\\\\\\\\"\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\`\\\\\\\\\\\\\\\"\\\\\\\"\\\"\""pwd"\"\\\"\\\\\\\"\\\\\\\\\\\\\\\"\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\`\\\\\\\\\\\\\\\"\\\\\\\\\\\\\\\`\\\\\\\\\\\\\\\"\\\\\\\"\\\\\\\`\\\\\\\"\\\"\\\`\\\"\"\`\""`"``
This works too.

**Comment by zoulasc** [comment]
Updated.

**Pull request closed without merging**
